---
title: "Diebold Chapter 10 Codes"
author: "Д. Хашбаатар"
output:
  html_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    highlight: tango
    number_sections: yes
    theme: "united"
    toc: yes
    toc_depth: 2
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
  word_document:
    toc: yes
    toc_depth: '2'
---

# Chapter 10 Codes

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(dplyr)     # data manipulation package   
library(forecast)  # Arima, auto.arima, forecast 
library(lubridate) # time manipulation
  
load("~/ecn321/pages/Lectures/ch10data.Rdata")
estimation_data <- ch10data %>% 
  filter(date > as.Date("1967-12-01") & date < as.Date("1994-01-01"))
estimation_data$lsales <- log(estimation_data$liquor)
head(estimation_data, 10) # ehnii 10 mor
```

```{r}
y <- estimation_data$lsales
time <- 1:length(y)
seasonal <- as.factor(month(estimation_data$date))
X <- cbind(time, time2 = time^2, model.matrix(~seasonal - 1))
```


## ARMA(3,0)

```{r}
reg <- Arima(y, order = c(3, 0, 0), xreg = X, include.mean = FALSE)
summary(reg)
```



```{r, eval=FALSE}
plot(estimation_data$date, y, type = "l", lwd = 2, xlab = "Time")
lines(estimation_data$date, y - residuals(reg), lty = 2, col = "red")
```


```{r, echo=FALSE}
library(dygraphs)
y1 <- ts(y, start = c(1968, 1), frequency = 12)
fit <- ts(y - residuals(reg),start = c(1968, 1), frequency = 12)
model <- cbind(y1, fit)
dygraph(model) %>% 
  dySeries("y1", label = "log of Liquor sales") %>%
  dySeries("fit", label = "Model Fit") %>% 
  dyOptions(colors = RColorBrewer::brewer.pal(2, "Set1")) %>% 
  dyRangeSelector()
```