---
title: "Diebold Chapter 7, 8 Codes"
author: "Д. Хашбаатар"
output:
  html_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    highlight: tango
    number_sections: yes
    theme: "united"
    toc: yes
    toc_depth: 2
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
  word_document:
    toc: yes
    toc_depth: '2'
---

```{r message=FALSE}
library(dplyr)
library(vars)
library(stargazer)
load("ch11data.Rdata")
plot(data11$date, data11$starts,
     type = "l", lty = 2, col="blue",
     xlab = "Date", ylab = "")
lines(data11$date, data11$comps)

```
```{r}
library(dplyr)
estimation_data <- filter(data11, date < as.Date("1992-01-01"))
estimation_data <- ts(estimation_data[,-1], start = c(1968, 1), freq=12)

```

## Lag Selection

```{r}
VARselect(estimation_data, lag.max=8,
  type="const")[["selection"]]

```

## Estimation

```{r}
var1 <- VAR(estimation_data, p=4, type="const")
```



```{r}
summary(var1)
```


$$\Phi_1 =
\begin{bmatrix} 0.237& 0.075 \\ 0.032  & 0.660 \end{bmatrix} $$

$$\Phi_2=
\begin{bmatrix}  0.206 & 0.040 \\ -0.121 & 0.230 \end{bmatrix} $$
$$\Phi_3=
\begin{bmatrix}  0.121 & 0.047 \\ -0.021 &  0.143* \end{bmatrix}$$
$$\Phi_4=
\begin{bmatrix}   0.157 & 0.047 \\ 0.082 &  0.008* \end{bmatrix}$$


## Var Cov

```{r}
summary(var1)$covres
```

```{r}
summary(var1)$corres
```

## Granger Causality

```{r}
causality(var1, cause = "starts")
```
```{r}
causality(var1, cause = "comps")
```


## IRF

```{r}
ir.1 <- irf(var1, impulse = "comps", response = "starts", n.ahead = 20, ortho = FALSE)
plot(ir.1)
```
```{r}
ir.2 <- irf(var1, impulse = "starts", response = "comps", n.ahead = 20, ortho = FALSE)
plot(ir.2)
```
```{r}
ir.3 <- irf(var1, impulse = "starts", response = "starts", n.ahead = 20, ortho = FALSE)
plot(ir.3)
```
```{r}
ir.4 <- irf(var1, impulse = "comps", response = "comps", n.ahead = 20, ortho = FALSE)
plot(ir.4)
```

## Forecast Error Variance Demposition

```{r}
fevd1 <- fevd(var1, n.ahead=20)
plot(fevd1)
```

```{r}
library(forecast)
forecast(var1,h=12)
```

```{r}
plot(forecast(var1,h=12))
```

