---
title: "Бие даалт - 1"
author: ""
date: "9/30/2019"
output: html_document
---
Дараахи дасгалуудыг гүйцэтгэн гаргацтай, цэвэр бичин хураалгана уу! 

<span style="color:red">Deadline: 2019-10-7</span> 

## 1. Магадлалын онол, статистикийн мэдлэгээ бататгах

Wooldridge "Introductory Econometrics" номын Appendix B, Appendix C-г сайтар уншин, бүлэг бүрийн дасгал бодлогыг ажилла.

## 2. Аналитик Дасгалууд

### 1

$$x_t=\epsilon_t -0.5 \epsilon_{t-1}+0.5 \epsilon_{t-2},\quad \epsilon_t\sim iid(0,1)$$
гэж тодорхойльё.

 a.  $\mathrm{E}(x_t )$ $Var(x_t )$-г ол.  $t$-ээс хамаарах уу?
 b. $Cor(x_t , x_{t-1} )$,  $Cor(x_t , x_{t-2} )$-г ол 
 c. $h> 2$ бол $Cor(x_ t , x_{t-h} )$-г ол

### 2

Дараахи $AR(1)$ загварыг авч үзье 
$$Y_t = \phi_0 + \phi_1 Y_{t - 1} + u_t.$$ Энэ процесс стационарь бол

 a.  $\mathrm{E}(Y_t ) = \mathrm{E}(Y_{t - 1})$ байxыг үзүүл. 
 b. $\mathrm{E}(Y_t ) = \phi_0/(1 - \phi_1 )$ болохыг үзүүл.

### 3

$Y_t$ нь $AR(1)$ цуваа 
$$Y_ t = 2.5 + 0.7Y_{t - 1} + u_ t,\quad u_ t \sim iid (0, 9).$$

 a. $Y_t$-ийн дундаж болон вариацыг тооц.
 b. $Y_ t$-ийн эхний 2 автоковариацыг тооц.
 c. $Y_ t$-ийн эхний 2 автокорреляцыг тооц .
 d. $Y_ T = 102.3$ бол $Y_{T + 1,  T} = \mathrm{E}(Y_ {T + 1} | Y_{T} , Y_{T - 1} , \ldots)$-г ол

### 4 

Нөхцөлт дундаж болон, таамаглалын талаархи дараахи өгүүлбэрүүдийг батал

 a.  $W\sim (\mu_W, \sigma^2_W)$ (дундаж $\mu_W$, вариац $\sigma^2_W$) байх санамсаргүй хэмжигдэхүүн, $c$ тогтмол тоо бол  $\mathrm{E}(W - c)^2 = \sigma^2_W + (\mu_W - c)^2$ байна.

 b. Хугацаан цуваа $Y_ t$ -г таамаглах тухай авч үзье.
$f_{t - 1}$ нь $t-1$-хугацаа хүртэлх мэдээлэл $\Omega_t=\{Y_{t-1} , Y_{t - 2} , \ldots\}$-г ашигласан $Y_ t$-ийн таамаглал гэе.  Тэгвэл таамаглалын алдааны квадратын нөхцөлт дундаж (conditional mean squared error) $$\mathrm{E}((Y_ t - f_{t - 1} )^2|\Omega_t)$$  нь $f_{t - 1} = \mathrm{E}(Y_t |\Omega_{t - 1})$ үед хамгийн бага утгаа авна.
