---
title: "Бие даалт - 1"
author: ""
date: ""
output: html_document
---

 - Бие даалтыг санамсаргүйгээр 1-3 асуулт сонгон, 11/20 өдөр ангид бичгээр шалгаж, дүгнэнэ.
 - Бие даалтыг группээр хэлэлцэж хийх боломжтой бөгөөд оюутан бүр өөрийн даалгаварыг `word` юмуу `pdf` хэлбэрээр `hashbaatar@gmail.com` хаяг руу явуулна. 
 - <span style="color:red">ХУРААЛГАХ ХУГАЦАА: 2019-11-19</span> 

# Аналитик Дасгалууд

## A. 1

$$y_t=\phi_1 y_{t-1}+\cdots+\phi_py_{t-p}+u_t$$
Дээрхи AR(p) процессийг
$$\Delta y_t=\delta y_{t-1}+\gamma_1 \Delta y_{t-1}+\cdots+\gamma_{p-1} \Delta y_{t-p+1}+\varepsilon_t$$
хэлбэрт хувирга.

## A. 2

 Дараах хоёр хувьсагч бүхий  загварыг авч үзье.
 $$\begin{pmatrix}y_{1,t}\\ y_{2,t}\end{pmatrix}=\begin{pmatrix}0.6&0.2\\-0.1&0.7\end{pmatrix}\begin{pmatrix}y_{1,t-1}\\ y_{2,t-1}\end{pmatrix}+\begin{pmatrix}\varepsilon_{1,t}\\ \varepsilon_{2,t}\end{pmatrix},\quad\begin{pmatrix}\varepsilon_{1,t}\\ \varepsilon_{2,t}\end{pmatrix}\sim N(\boldsymbol{0}, \Sigma_\varepsilon),\quad \Sigma_\varepsilon=\begin{pmatrix}9&2\\2&4\end{pmatrix}$$
  
  a. Энэ загвар тогтвортой гэсэн нөхцөлийг хангах уу? Яагаад тийм, эсвэл үгүй гэх үндэслэлээ тайлбарлаарай.
  
  b. Төгсгөлгүй эрэмбийн хөдөлгөөнт дунджийн дүрслэл хэлбэрээр уг загварыг бичнэ үү.
  
  c. Нэг стандарт алдааны шокын хувьд эхний арван таван хугацаа-ны импульсын хариу үйлдлийн функцүүдийг тооцно уу.
    

# Симуляцийн бодлого

## S.1 

Дараах aвторегрессив загварыг ашиглан 777 өгөгдлийг симуляц хийх замаар үүсгэнэ үү.
$$y_t=0.7y_{t-1}+\varepsilon_t,\quad \varepsilon\sim N(0,1),\quad y_0=0$$
    
 a. Цуваа бүрийн нөхцөлт бус дундаж болон вариацыг олно уу.
 b. Цуваа бүрийн хувьд $j$–р эрэмбийн автокорреляцыг олно уу.
 c. Симуляц хийж үүсгэсэн цувааг графикт дүрсэлнэ үү.
 d. Үүсгэсэн түүврийн сүүлийн ажиглалтыг ашиглан  нэг алхамын дараах (нэг хугацааны дараах) таамаглалыг тооцно уу.
 e. Симуляц хийж үүсгэсэн өгөгдлөө ашиглан  дахь ажиглалтын хувьд нэг алхамын дараах нөхцөлт тархалтыг олно уу.
 f. Энэхүү нэг алхамын дараах таамаглалын 95 хувийн итгэх интервалыг байгуулна уу.
 g. Симуляцын үр дүнд үүсгэсэн өгөгдөл бүрийг ашиглан  AR(1) загварыг үнэлнэ үү. Үнэлсэн загваруудын үлдэгдлийг шинжилж, дүгнэлт хийнэ үү.

## S.2 

$y_t=ϕy_{t−1}+u_t$,(T=1000) -г шугаман регрессээр үнэлэхэд гарах налалтын коэффициентийн $t$-утгын тархалтыг

 a. $ϕ=0.6$

 b. $ϕ=1$ тус бүрийн хувьд симуляцын аргаар ол. Үүнд, хистограммыг байгуулан, 0.025,0.05,0.1,0.9,0.975 квантилуудыг тооц. Симуляцийн тоо `nsim=10000`. 
 

# Сурах бичгийн дасгал

## C. 1
Үндсэн сурах бичгийн Бүлэг 6-д авч үзсэн шинэ орон сууцны тоог таамаглах жишээний загварыг авч үзье.

a. Уг загвар (мөчлөгийг авч үзээгүй)-ын хувьд CUSUM (Cumulative Sum) шинжилгээг хийж, дүгнэлт хийнэ үү.
b. Одоо энэ загварын хувьд мөчлөгийг нэмж загварчилж, үнэлгээг хийнэ үү.
b. Хэсэг (b)-д үнэлсэн загварын хувьд CUSUM шинжилгээг хийж, үр дүнг Хэсэг (a)-тай харьцуулж, дүгнэнэ үү.

## C.2

Сурах бичгийн дараах дасгалуудыг гүйцэтгэ

 a. Бүлэг 7, 7.3.
 b. Бүлэг 8, 8.5.
 c. Бүлэг 11, 11.10.
 d. Бүлэг 11, 11.11.