---
title: "Бие даалт - 3 (Take Home Exam)"
author: ""
date: ""
output: html_document
---

 - Гэрийн даалгаварыг санамсаргүйгээр 1-3 асуулт сонгон, 12/18 өдөр ангид бичгээр шалгаж, дүгнэнэ.
 - Гэрийн даалгаварыг группээр хэлэлцэж хийх боломжтой бөгөөд оюутан бүр өөрийн даалгаварыг Rmarkdown ашиглан гүйцэтгэн `word` юмуу `pdf` хэлбэрээр `hashbaatar@gmail.com` хаяг руу явуулна. 
 - <span style="color:red">ХУРААЛГАХ ХУГАЦАА: 2019-12-17</span> 

# Аналитик Дасгалууд

## A. 1

$$y_t=\phi_1 y_{t-1}+\phi_2y_{t-2}+\epsilon_t$$
процесс стационарь байхын тулд $ϕ_1$, $ϕ_2$-ууд ямар нөхцлийг хангах вэ? Авч болох утгуудыг графикт үзүүл.
хэлбэрт хувирга.

## A. 2

 ${y_t }$, ${z_t }$ нь $I(1)$ цуваанууд бөгөөд $y-\beta z_t$ нь I(0) ($\beta\neq 0$) бол $\delta\neq\beta$ байх үед $y_t -\delta z_t$ нь $I(1)$ болохыг үзүүл.    

## S.1 

Түүврийн хэмжээ $T= 50, 100, 200, 400, 800$  $ρ_1$ and $ρ_2$ : {−0.7, 0.0, 0.7, 1} утгуудын хувьд дараахи 2 цувааг үүсгэ.
$$y_t = ρ_1 y_{t−1} + u_{t1},\quad y_0 = 0,\quad u_{t1} ∼ NID(0, 1)$$
$$x_t = ρ_2 x_{t−1} + u_{t2},\quad x_0 = 0,\quad u_{t2} ∼ NID(0, 1),$$

$y_t$-г $x_t$т регрессдэн($y=\beta_1+\beta_2x+e$)  нийт симуляцын хэдэн хувьд  $H_:β_2 = 0 .05$ таамаглалыг 0.05 итгэх түвшинд няцааж буйг илтгэ.

5 түүврийн хэмжээ бүрийн хувьд нийт туршилтын тоо 16, туршилтын давталт 10000 гэдгийг анхаарна уу.
 $ρ_1$ and $ρ_2$ -ийн ямар утгуудын хувьд дээрхи spurious regression-г зөв таниж байна вэ? 
 
# Сурах бичгийн дасгал

## C. 1

Wooldridge сурах бичгийн 18.1-18.9 бодлогуудыг бод

## C.2

Wooldridge сурах бичгийн 18.C1 - 18.C15 бодлогуудыг бод